services:
  detector-pose:
    build: 
      context: .
      dockerfile: detector_pose/Dockerfile
    ports:
      - "8011:8011"
    volumes:
      - shared_images:/app/output_image
      - ./logs:/app/logs
    environment:
      - ALERT_SERVICE_URL=http://alert-logic:8012/alert
      - PYTHONPATH=/app
      - OUTPUT_DIR=/app/output_image
    networks:
      - pose-net

  alert-logic:
    build: 
      context: .
      dockerfile: alert_logic/Dockerfile
    ports:
      - "8012:8012"
    volumes:
      - shared_images:/app/output_image
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - OUTPUT_DIR=/app/output_image
    networks:
      - pose-net

networks:
  pose-net:
    driver: bridge

volumes:
  shared_images:
  logs:
