services:
  detector-pose:
    build: 
      context: .
      dockerfile: detector_pose/Dockerfile
    ports:
      - "8011:8011"
    volumes:
      - ./output_image:/app/output_image:rw
      - ./logs:/app/logs:rw
    environment:
      - ALERT_SERVICE_URL=http://alert-logic:8012/alert
      - PYTHONPATH=/app
      - OUTPUT_DIR=/app/output_image
      - YOLO_CONFIG_DIR=/app/detector_pose/.config/Ultralytics
    networks:
      - pose-net
    user: "1000:1000"

  alert-logic:
    build: 
      context: .
      dockerfile: alert_logic/Dockerfile
    ports:
      - "8012:8012"
    volumes:
      - ./output_image:/app/output_image:rw
      - ./logs:/app/logs:rw
    environment:
      - PYTHONPATH=/app
      - OUTPUT_DIR=/app/output_image
    networks:
      - pose-net  # Changed from 'pose' to 'pose-net' to match

networks:
  pose-net:
    driver: bridge

volumes:
  logs:
